#	$NetBSD$

INCSDIR= /usr/include/evbcputwo

INCS=	ansi.h aout_machdep.h asm.h atomic.h \
	bswap.h bus_defs.h bus_funcs.h bus.h byte_swap.h \
	cdefs.h cpu_counter.h cpu.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian_machdep.h endian.h \
	fenv.h float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h \
	limits.h lock.h \
	math.h mcontext.h mutex.h \
	param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h sysarch.h \
	trap.h types.h \
	userret.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
